### PR TITLE
common/gadi/packages.yaml: use system openmpi directly

### PR DESCRIPTION
**Pull request by harshula**
* This commit requires https://github.com/ACCESS-NRI/spack-packages/pull/66 for ACCESS-OM2 to build on Gadi.

### CODE REVIEW

**Comment by harshula** [comment]
Hi @CodeGat , This commit will require https://github.com/ACCESS-NRI/ACCESS-OM2/blob/main/spack.yaml to be updated. i.e. `s/nci-openmpi/openmpi/` .

**Comment by harshula** [comment]
This whole set of changes were triggered by https://github.com/ACCESS-NRI/spack-packages/issues/61 .

**Comment by harshula** [comment]
The following instructions will need to be updated:
https://forum.access-hive.org.au/t/how-to-build-access-om2-on-gadi/1545
https://github.com/ACCESS-NRI/spack-config/issues/5

**Comment by harshula** [comment]
Testing: https://github.com/ACCESS-NRI/spack-packages/pull/66#issuecomment-1955221166

**Review by CodeGat — APPROVED** [review]
LGTM

**Pull request merged**
