### PR TITLE
Add a directory for Spack v0.21

### PR DESCRIPTION
**Pull request by harshula**
[Updated: 24/01/2024: Fixed a bug: missing v0.20/gadi/linux/compilers.yaml]

This PR results in the following layout:
```
|-- common
|   |-- ci
|   |   `-- packages.yaml
|   |-- concretizer.yaml
|   |-- config.yaml
|   |-- gadi
|   |   |-- linux
|   |   |   `-- compilers.yaml
|   |   `-- packages.yaml
|   |-- modules.yaml
|   `-- repos.yaml
|-- v0.20
|   |-- ci
|   |   |-- concretizer.yaml -> ../../common/concretizer.yaml
|   |   |-- config.yaml -> ../../common/config.yaml
|   |   |-- modules.yaml -> ../../common/modules.yaml
|   |   |-- packages.yaml -> ../../common/ci/packages.yaml
|   |   `-- repos.yaml -> ../../common/repos.yaml
|   `-- gadi
|       |-- concretizer.yaml -> ../../common/concretizer.yaml
|       |-- config.yaml -> ../../common/config.yaml
|       |-- linux
|       |   `-- compilers.yaml -> ../../../common/gadi/linux/compilers.yaml
|       |-- modules.yaml -> ../../common/modules.yaml
|       |-- packages.yaml -> ../../common/gadi/packages.yaml
|       `-- repos.yaml -> ../../common/repos.yaml
`-- v0.21
    |-- ci
    |   |-- concretizer.yaml -> ../../common/concretizer.yaml
    |   |-- config.yaml -> ../../common/config.yaml
    |   |-- modules.yaml -> ../../common/modules.yaml
    |   |-- packages.yaml -> ../../common/ci/packages.yaml
    |   `-- repos.yaml -> ../../common/repos.yaml
    `-- gadi
        |-- concretizer.yaml -> ../../common/concretizer.yaml
        |-- config.yaml -> ../../common/config.yaml
        |-- linux
        |   `-- compilers.yaml -> ../../../common/gadi/linux/compilers.yaml
        |-- modules.yaml -> ../../common/modules.yaml
        |-- packages.yaml -> ../../common/gadi/packages.yaml
        `-- repos.yaml -> ../../common/repos.yaml
```

### CODE REVIEW

**Comment by harshula** [comment]
The old layout looked like:
```
`-- v0.20
    |-- ci
    |   |-- concretizer.yaml -> ../common/concretizer.yaml
    |   |-- config.yaml
    |   |-- modules.yaml -> ../common/modules.yaml
    |   |-- packages.yaml
    |   `-- repos.yaml -> ../common/repos.yaml
    |-- common
    |   |-- concretizer.yaml
    |   |-- modules.yaml
    |   `-- repos.yaml
    `-- gadi
        |-- concretizer.yaml -> ../common/concretizer.yaml
        |-- config.yaml
        |-- linux
        |   `-- compilers.yaml
        |-- modules.yaml -> ../common/modules.yaml
        |-- packages.yaml
        `-- repos.yaml -> ../common/repos.yaml
```

**Comment by harshula** [comment]
## Testing - Docker
```
[root@63e462cc2c25 spack]# spack --version
0.20.3 (6812713cf470b473a607f0de0e8e1cf53f804fb7)

[root@63e462cc2c25 spack]# ls -l /opt/spack-config/v0.20/ci/
total 0
lrwxrwxrwx 1 root root 29 Jan 23 04:00 concretizer.yaml -> ../../common/concretizer.yaml
lrwxrwxrwx 1 root root 24 Jan 23 04:00 config.yaml -> ../../common/config.yaml
lrwxrwxrwx 1 root root 25 Jan 23 04:00 modules.yaml -> ../../common/modules.yaml
lrwxrwxrwx 1 root root 29 Jan 23 04:00 packages.yaml -> ../../common/ci/packages.yaml
lrwxrwxrwx 1 root root 23 Jan 23 04:00 repos.yaml -> ../../common/repos.yaml

[root@63e462cc2c25 spack]# ls -l /opt/spack/etc/spack/
total 4
lrwxrwxrwx 1 root root   45 Jan 23 04:00 concretizer.yaml -> ../../../spack-config/common/concretizer.yaml
lrwxrwxrwx 1 root root   40 Jan 23 04:00 config.yaml -> ../../../spack-config/common/config.yaml
drwxr-xr-x 6 root root 4096 Jan 23 04:00 defaults
lrwxrwxrwx 1 root root   41 Jan 23 04:00 modules.yaml -> ../../../spack-config/common/modules.yaml
lrwxrwxrwx 1 root root   45 Jan 23 04:00 packages.yaml -> ../../../spack-config/common/ci/packages.yaml
lrwxrwxrwx 1 root root   39 Jan 23 04:00 repos.yaml -> ../../../spack-config/common/repos.yaml

[root@63e462cc2c25 spack]# spack find
-- linux-rocky8-x86_64 / gcc@8.5.0 ------------------------------
intel-oneapi-compilers@2021.2.0  patchelf@0.17.2

-- linux-rocky8-x86_64 / intel@2021.2.0 -------------------------
autoconf@2.69                       libevent@2.1.12    openssl@1.1.1t
automake@1.16.5                     libiconv@1.17      perl@5.26.3
bison@3.8.2                         libpciaccess@0.17  pigz@2.7
bzip2@1.0.8                         libsigsegv@2.14    pkgconf@1.9.5
ca-certificates-mozilla@2023-01-10  libtool@2.4.7      pmix@4.2.3
cmake@3.24.2                        libxcrypt@4.4.33   tar@1.34
diffutils@3.9                       libxml2@2.10.3     util-macros@1.19.3
gettext@0.21.1                      m4@1.4.19          xz@5.4.1
gmake@4.4.1                         ncurses@6.4        zlib@1.2.13
hwloc@2.9.1                         numactl@2.0.14     zstd@1.5.5
krb5@1.20.1                         openmpi@4.0.2
libedit@3.1-20210216                openssh@9.3p1
==> 36 installed packages
```

```
[root@6941c4b44a9b spack]# spack --version
0.21.1 (e30fedab102f9281a220fb4fae82e3f8c43a82ac)

[root@6941c4b44a9b spack]# ls -l /opt/spack-config/v0.21/ci/
total 0
lrwxrwxrwx 1 root root 29 Jan 23 04:52 concretizer.yaml -> ../../common/concretizer.yaml
lrwxrwxrwx 1 root root 24 Jan 23 04:52 config.yaml -> ../../common/config.yaml
lrwxrwxrwx 1 root root 25 Jan 23 04:52 modules.yaml -> ../../common/modules.yaml
lrwxrwxrwx 1 root root 29 Jan 23 04:52 packages.yaml -> ../../common/ci/packages.yaml
lrwxrwxrwx 1 root root 23 Jan 23 04:52 repos.yaml -> ../../common/repos.yaml

[root@6941c4b44a9b spack]# ls -l /opt/spack/etc/spack/
total 4
lrwxrwxrwx 1 root root   45 Jan 23 04:52 concretizer.yaml -> ../../../spack-config/common/concretizer.yaml
lrwxrwxrwx 1 root root   40 Jan 23 04:52 config.yaml -> ../../../spack-config/common/config.yaml
drwxr-xr-x 6 root root 4096 Jan 23 04:52 defaults
lrwxrwxrwx 1 root root   41 Jan 23 04:52 modules.yaml -> ../../../spack-config/common/modules.yaml
lrwxrwxrwx 1 root root   45 Jan 23 04:52 packages.yaml -> ../../../spack-config/common/ci/packages.yaml
lrwxrwxrwx 1 root root   39 Jan 23 04:52 repos.yaml -> ../../../spack-config/common/repos.yaml

[root@6941c4b44a9b spack]# spack find
-- linux-rocky8-x86_64 / gcc@8.5.0 ------------------------------
gmake@4.4.1  intel-oneapi-compilers@2021.2.0  patchelf@0.17.2

-- linux-rocky8-x86_64 / intel@2021.2.0 -------------------------
autoconf@2.69                       libedit@3.1-20210216  openssh@9.5p1
automake@1.16.5                     libevent@2.1.12       openssl@3.1.3
bison@3.8.2                         libiconv@1.17         perl@5.26.3
bzip2@1.0.8                         libpciaccess@0.17     pigz@2.7
ca-certificates-mozilla@2023-05-30  libsigsegv@2.14       pkgconf@1.9.5
cmake@3.24.2                        libtool@2.4.7         pmix@4.2.2
curl@8.4.0                          libxcrypt@4.4.35      tar@1.34
diffutils@3.9                       libxml2@2.10.3        util-macros@1.19.3
findutils@4.9.0                     m4@1.4.19             xz@5.4.1
gettext@0.22.3                      ncurses@6.4           zlib-ng@2.1.4
gmake@4.4.1                         nghttp2@1.57.0        zstd@1.5.5
hwloc@2.9.1                         numactl@2.0.14
krb5@1.20.1                         openmpi@4.0.2
==> 40 installed packages
```

**Comment by harshula** [comment]
## Testing - Gadi
```
[test-v0.20-nci-openmpi]$ spack --version
0.20.3 (6812713cf470b473a607f0de0e8e1cf53f804fb7)

[test-v0.20-nci-openmpi]$ ls -l spack-config/v0.20/gadi/*
lrwxrwxrwx 1 user group   29 Jan 24 13:05 spack-config/v0.20/gadi/concretizer.yaml -> ../../common/concretizer.yaml
lrwxrwxrwx 1 user group   24 Jan 24 13:05 spack-config/v0.20/gadi/config.yaml -> ../../common/config.yaml
lrwxrwxrwx 1 user group   25 Jan 24 13:05 spack-config/v0.20/gadi/modules.yaml -> ../../common/modules.yaml
lrwxrwxrwx 1 user group   31 Jan 24 13:05 spack-config/v0.20/gadi/packages.yaml -> ../../common/gadi/packages.yaml
lrwxrwxrwx 1 user group   23 Jan 24 13:05 spack-config/v0.20/gadi/repos.yaml -> ../../common/repos.yaml

spack-config/v0.20/gadi/linux:
total 0
lrwxrwxrwx 1 user group 41 Jan 24 13:05 compilers.yaml -> ../../../common/gadi/linux/compilers.yaml

[test-v0.20-nci-openmpi]$ ls -l spack/etc/spack/
total 4
lrwxrwxrwx 1 user group   45 Jan 24 13:06 concretizer.yaml -> ../../../spack-config/common/concretizer.yaml
lrwxrwxrwx 1 user group   40 Jan 24 13:06 config.yaml -> ../../../spack-config/common/config.yaml
drwxr-sr-x 6 user group 4096 Jan 24 13:05 defaults
lrwxrwxrwx 1 user group   38 Jan 24 13:06 linux -> ../../../spack-config/v0.20/gadi/linux
lrwxrwxrwx 1 user group   41 Jan 24 13:06 modules.yaml -> ../../../spack-config/common/modules.yaml
lrwxrwxrwx 1 user group   47 Jan 24 13:06 packages.yaml -> ../../../spack-config/common/gadi/packages.yaml
lrwxrwxrwx 1 user group   39 Jan 24 13:06 repos.yaml -> ../../../spack-config/common/repos.yaml

[test-v0.20-nci-openmpi]$ spack find
-- linux-rocky8-x86_64 / intel@19.0.5.281 -----------------------
access-om2@latest       gmake@4.4.1          mom5@master           oasis3-mct@master
cice5@master            hdf5@1.14.1-2        nci-openmpi@4.0.2     parallelio@2.5.2
cmake@3.24.2            json-fortran@8.3.0   netcdf-c@4.7.4        pkgconf@1.9.5
datetime-fortran@1.7.0  libaccessom2@master  netcdf-fortran@4.5.2  zlib@1.2.13
==> 16 installed packages
```

```
[test-v0.21-openmpi]$ spack --version
0.21.1 (e30fedab102f9281a220fb4fae82e3f8c43a82ac)

[test-v0.21-openmpi]$ ls -l spack-config/v0.21/gadi/*
lrwxrwxrwx 1 user group   29 Jan 23 22:18 spack-config/v0.21/gadi/concretizer.yaml -> ../../common/concretizer.yaml
lrwxrwxrwx 1 user group   24 Jan 23 22:18 spack-config/v0.21/gadi/config.yaml -> ../../common/config.yaml
lrwxrwxrwx 1 user group   25 Jan 23 22:18 spack-config/v0.21/gadi/modules.yaml -> ../../common/modules.yaml
lrwxrwxrwx 1 user group   31 Jan 23 22:18 spack-config/v0.21/gadi/packages.yaml -> ../../common/gadi/packages.yaml
lrwxrwxrwx 1 user group   23 Jan 23 22:18 spack-config/v0.21/gadi/repos.yaml -> ../../common/repos.yaml

spack-config/v0.21/gadi/linux:
total 0
lrwxrwxrwx 1 user group 41 Jan 23 22:18 compilers.yaml -> ../../../common/gadi/linux/compilers.yaml

[test-v0.21-openmpi]$ ls -l spack/etc/spack/
total 4
lrwxrwxrwx 1 user group   45 Jan 23 22:20 concretizer.yaml -> ../../../spack-config/common/concretizer.yaml
lrwxrwxrwx 1 user group   40 Jan 23 22:20 config.yaml -> ../../../spack-config/common/config.yaml
drwxr-sr-x 6 user group 4096 Jan 23 22:19 defaults
lrwxrwxrwx 1 user group   38 Jan 23 22:20 linux -> ../../../spack-config/v0.21/gadi/linux
lrwxrwxrwx 1 user group   41 Jan 23 22:20 modules.yaml -> ../../../spack-config/common/modules.yaml
lrwxrwxrwx 1 user group   47 Jan 23 22:20 packages.yaml -> ../../../spack-config/common/gadi/packages.yaml
lrwxrwxrwx 1 user group   39 Jan 23 22:20 repos.yaml -> ../../../spack-config/common/repos.yaml

[test-v0.21-openmpi]$ spack find
-- linux-rocky8-x86_64_v4 / intel@19.0.5.281 --------------------
access-om2@latest                   krb5@1.20.1           oasis3-mct@master
autoconf@2.69                       libaccessom2@master   openmpi@4.0.2
automake@1.16.5                     libedit@3.1-20210216  openssh@9.5p1
bison@3.8.2                         libevent@2.1.12       openssl@3.1.3
bzip2@1.0.8                         libiconv@1.17         parallelio@2.5.2
ca-certificates-mozilla@2023-05-30  libpciaccess@0.17     perl@5.26.3
cice5@master                        libsigsegv@2.14       pigz@2.7
cmake@3.24.2                        libtool@2.4.7         pkgconf@1.9.5
datetime-fortran@1.7.0              libxcrypt@4.4.35      pmix@4.2.2
diffutils@3.9                       libxml2@2.10.3        tar@1.34
findutils@4.9.0                     m4@1.4.19             util-macros@1.19.3
gettext@0.22.3                      mom5@master           xz@5.4.1
gmake@4.4.1                         ncurses@6.4           zlib-ng@2.1.4
hdf5@1.14.3                         netcdf-c@4.7.4        zstd@1.5.5
hwloc@2.9.1                         netcdf-fortran@4.5.2
json-fortran@8.3.0                  numactl@2.0.14
==> 46 installed packages
```

**Comment by CodeGat** [comment]
Just to confirm @harshula - the `v0.20` and `v0.21` versions of `spack` do not differ in config?

**Comment by harshula** [comment]
> Just to confirm @harshula - the `v0.20` and `v0.21` versions of `spack` do not differ in config?

At the moment, yes. It may diverge in the future.

**Review by CodeGat — APPROVED** [review]
Setup is logical. Remember to tag this version if it's one you would like to include in future deployments of `access-om2` (or any model, really)

**Pull request merged**
