### PR TITLE
common/modules.yaml: change projection to: {name}/{version}-{hash:7}

### PR DESCRIPTION
**Pull request by harshula**
* Do not set conflict & environment variables in the default configuration.

### CODE REVIEW

**Comment by aidanheerdegen** [comment]
This is related to https://github.com/ACCESS-NRI/build-cd/issues/157 right?

Can you add some detail about why these changes are required?

**Comment by harshula** [comment]
The Issue https://github.com/ACCESS-NRI/build-cd/issues/157 describes a bug found by the Model Development team as a result of the `{name}/{version}` format of the modulefile. To avoid this in the future, we need to include a string that ensures a package built with a different variant has a unique name. This can be achieved by using Spack's default mechanism of a Spack hash as a suffix. This change takes us closer to Spack defaults.

The conflict & environment variables should not have been included in the original commit.

**Comment by harshula** [comment]
**Testing**

In a container, I tested the changes in this PR alongside a `spack.yaml` that looks like:
```
  modules:
    default:
      enable:
        - tcl
      tcl:
        include:
          - access-om2
          - mom5
          - cice5
          - libaccessom2
          - oasis3-mct
        projections:
          all: '{name}/{version}-{hash:7}'
          access-om2: '{name}/2024.03.0'
          cice5: '{name}/2023.10.19-{hash:7}'
          mom5: '{name}/2024.08.23-{hash:7}'
          libaccessom2: '{name}/2023.10.26-{hash:7}'
          oasis3-mct: '{name}/2023.11.09-{hash:7}'
```

and got the following result:
```
# ls ../release/modules/linux-rocky8-x86_64/*
../release/modules/linux-rocky8-x86_64/access-om2:
2024.03.0

../release/modules/linux-rocky8-x86_64/cice5:
2023.10.19-ev4dvii

../release/modules/linux-rocky8-x86_64/libaccessom2:
2023.10.26-3vliquc

../release/modules/linux-rocky8-x86_64/mom5:
2024.08.23-iv4bvxy

../release/modules/linux-rocky8-x86_64/oasis3-mct:
2023.11.09-ruyz6py
```

**Comment by harshula** [comment]
**Testing on Gadi**

```
  modules:
    default:
      enable:
        - tcl
      tcl:
        include:
          - access-om2
          - mom5
          - cice5
          - libaccessom2
          - oasis3-mct
        projections:
          all: '{name}/{version}-{hash:7}'
          access-om2: '{name}/2024.03.0'
          cice5: '{name}/2023.10.19-{hash:7}'
          mom5: '{name}/2024.08.23-{hash:7}'
          libaccessom2: '{name}/2023.10.26-{hash:7}'
          oasis3-mct: '{name}/2023.11.09-{hash:7}'
```

```
$ ls release/modules/linux-rocky8-x86_64/*
release/modules/linux-rocky8-x86_64/access-om2:
2024.03.0

release/modules/linux-rocky8-x86_64/cice5:
2023.10.19-epnbkes

release/modules/linux-rocky8-x86_64/libaccessom2:
2023.10.26-l6hmysz

release/modules/linux-rocky8-x86_64/mom5:
2024.08.23-oi2lpoe

release/modules/linux-rocky8-x86_64/oasis3-mct:
2023.11.09-uymfvj3
```

**Comment by aidanheerdegen** [comment]
And just to be explicit, `release/modules/linux-rocky8-x86_64/access-om2/2024.03.0` correctly loads all the model component modules with their `{hash:7}` suffix?

**Comment by harshula** [comment]
```
$ module show access-om2/2024.03.0
-------------------------------------------------------------------
/g/data/[...]/test-v0.22-modules/release/modules/linux-rocky8-x86_64/access-om2/2024.03.0:

module-whatis   {ACCESS-OM2 bundle contains the coupled CICE5 and MOM5 models.}
module          load cice5/2023.10.19-epnbkes
module          load libaccessom2/2023.10.26-l6hmysz
module          load mom5/2024.08.23-oi2lpoe
prepend-path    CMAKE_PREFIX_PATH /g/data/[...]/test-v0.22-modules/release/linux-rocky8-x86_64/intel-19.0.5.281/access-om2-git.2024.03.0_2024.03.0-umtohlzff2aqbtd3h7ysqc262a4synzv/.
-------------------------------------------------------------------

$ module load access-om2/2024.03.0
Loading access-om2/2024.03.0
  Loading requirement: oasis3-mct/2023.11.09-uymfvj3
    libaccessom2/2023.10.26-l6hmysz cice5/2023.10.19-epnbkes
    mom5/2024.08.23-oi2lpoe

$ module unload access-om2/2024.03.0
Unloading access-om2/2024.03.0
  Unloading useless requirement: cice5/2023.10.19-epnbkes
    mom5/2024.08.23-oi2lpoe libaccessom2/2023.10.26-l6hmysz
    oasis3-mct/2023.11.09-uymfvj3
```

**Review by aidanheerdegen — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
